#!/bin/bash -e

# fahviewer postflight/postinstall

D="/Applications/Folding@home"
if [ -d "$D" ]; then
    chmod 0755 "$D"
else
    mkdir -m 0755 "$D"
fi

SCRIPTS="$(dirname "$0")"
"$SCRIPTS"/onquit
